Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2022-05, with the labels that each got.

#358 Bug/multitenant anonymous application create
  forms-flow-api/src/formsflow_api/services/application.py
Labels: python

#364 Tenant specific process start call
  forms-flow-api/src/formsflow_api/models/application.py
  forms-flow-api/src/formsflow_api/models/form_process_mapper.py
  forms-flow-api/src/formsflow_api/services/application.py
  forms-flow-api/src/formsflow_api/services/external/bpm.py
  forms-flow-api/tests/unit/api/test_application.py
Labels: python

#386 adding eslint to web-ci
  .github/workflows/forms-flow-web-ci.yml
  forms-flow-web/package.json
  forms-flow-web/src/_tests_/test-components/test-error/index.test.js
  forms-flow-web/src/_tests_/test-components/test-form/stepper.test.js
  forms-flow-web/src/_tests_/test-components/test-serviceflow/constants.js
Labels: bug, javascript

#390 Fwf 1307/web tenant authentication (#4)
  deployment/docker/docker-compose-linux.yml
  deployment/docker/docker-compose-windows.yml
  forms-flow-web/Dockerfile
  forms-flow-web/README.md
  forms-flow-web/docker-compose.yml
  forms-flow-web/public/config/config.sample.js
  forms-flow-web/sample.env
  forms-flow-web/src/actions/actionConstants.js
  forms-flow-web/src/actions/tenantActions.js
  forms-flow-web/src/apiManager/services/formatterService.js
  forms-flow-web/src/apiManager/services/tenantServices.js
  forms-flow-web/src/components/Admin/index.js
  forms-flow-web/src/components/Application/ApplicationHistory.js
  forms-flow-web/src/components/Application/List.js
  forms-flow-web/src/components/Application/ViewApplication.js
  forms-flow-web/src/components/Application/historyTable.js
  forms-flow-web/src/components/Application/index.js
  forms-flow-web/src/components/Application/table.js
  forms-flow-web/src/components/BaseRouting.jsx
  forms-flow-web/src/components/Dashboard/Dashboard.js
  forms-flow-web/src/components/Form/Create.js
  forms-flow-web/src/components/Form/Item/Edit.js
  forms-flow-web/src/components/Form/Item/Preview.js
  forms-flow-web/src/components/Form/Item/Submission/Item/Edit.js
  forms-flow-web/src/components/Form/Item/Submission/Item/index.js
  forms-flow-web/src/components/Form/Item/Submission/List.js
  forms-flow-web/src/components/Form/Item/Submission/index.js
  forms-flow-web/src/components/Form/Item/View.js
  forms-flow-web/src/components/Form/Item/index.js
  forms-flow-web/src/components/Form/List.js
  forms-flow-web/src/components/Form/Stepper.js
  forms-flow-web/src/components/Form/index.js
  forms-flow-web/src/components/Insights/Insights.js
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
  forms-flow-web/src/components/ServiceFlow/filter/ServiceTaskFilterListDropDown.js
  forms-flow-web/src/components/ServiceFlow/index.js
  forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
  forms-flow-web/src/constants/constants.js
  forms-flow-web/src/containers/NavBar.jsx
  forms-flow-web/src/modules/index.js
  forms-flow-web/src/modules/tenantReducer.js
  forms-flow-web/src/services/UserService.js
Labels: bug, enhancement, javascript

#396 Response change for form_process_mapper put method
  forms-flow-api/src/formsflow_api/config.py
  forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
  forms-flow-api/src/formsflow_api/utils/translations/translations.py
  forms-flow-api/tests/unit/api/test_form_process_mapper.py
Labels: python

#410 application filter by application name made space insensitive
  forms-flow-api/src/formsflow_api/models/base_model.py
Labels: bug, python

#416 Data analysis API logging bugfix
  forms-flow-data-analysis-api/src/api/utils/logging.py
  forms-flow-data-analysis-api/tests/conftest.py
Labels: bug, python

#424 adding processTenant to application schema and application response
  forms-flow-api/src/formsflow_api/models/application.py
  forms-flow-api/src/formsflow_api/schemas/application.py
Labels: python

#401 tenant endpoint for process diagram
  forms-flow-web/src/apiManager/endpoints/index.js
  forms-flow-web/src/apiManager/services/formatterService.js
  forms-flow-web/src/apiManager/services/processServices.js
  forms-flow-web/src/components/Application/ViewApplication.js
  forms-flow-web/src/components/BPMN/ProcessDiagramHook.js
  forms-flow-web/src/components/Form/Item/Submission/List.js
  forms-flow-web/src/components/Form/Stepper.js
  forms-flow-web/src/components/Form/Steps/WorkFlow.js
  forms-flow-web/src/helper/helper.js
  forms-flow-web/src/modules/processReducer.js
Labels: javascript

#433 Fwf 1424/web versioning refactor
  forms-flow-web/src/apiManager/services/processServices.js
  forms-flow-web/src/components/Form/Create.js
  forms-flow-web/src/components/Form/Item/Edit.js
  forms-flow-web/src/components/Form/Stepper.js
Labels: javascript

#435 Tenant specific process diagram for tasks
  forms-flow-web/src/apiManager/services/formatterService.js
  forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
  forms-flow-web/src/components/ServiceFlow/details/TaskHeader.js
  forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
Labels: bug, javascript

#441 added missing uploaded form edge case for versioning
  forms-flow-web/src/components/Form/Item/Edit.js
  forms-flow-web/src/components/Form/Stepper.js
Labels: bug, javascript

#451 Bugfix - Version updating on making the form Anonymous
  forms-flow-web/src/components/Form/Item/Edit.js
Labels: bug, javascript

#450 applicationId regex query for submission list call
  forms-flow-web/src/components/Form/Item/Submission/List.js
Labels: bug, javascript

#454 solves FWF-1445
  forms-flow-web/src/components/Form/Item/Submission/Item/index.js
  forms-flow-web/src/components/Form/Item/Submission/index.js
  forms-flow-web/src/components/Form/List.js
Labels: javascript

#457 Task list bug in UI rendering
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/components/ServiceFlow/index.js
  forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
Labels: bug, javascript
