Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2022-06, with the labels that each got.

#476 Fwf 1333/application title per tenant
  deployment/docker/docker-compose.yml
  forms-flow-web/Dockerfile
  forms-flow-web/docker-compose.yml
  forms-flow-web/src/_tests_/test-containers/navbar.test.js
  forms-flow-web/src/actions/actionConstants.js
  forms-flow-web/src/actions/tenantActions.js
  forms-flow-web/src/apiManager/endpoints/config.js
  forms-flow-web/src/apiManager/endpoints/index.js
  forms-flow-web/src/apiManager/services/tenantServices.js
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/containers/NavBar.jsx
  forms-flow-web/src/modules/tenantReducer.js
Labels: enhancement, javascript

#508 WebAPI: Formio form creation
  deployment/docker/docker-compose.yml
  forms-flow-api/docker-compose.yml
  forms-flow-api/requirements.txt
  forms-flow-api/requirements/prod.txt
  forms-flow-api/sample.env
  forms-flow-api/src/formsflow_api/app.py
  forms-flow-api/src/formsflow_api/config.py
  forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
  forms-flow-api/src/formsflow_api/services/__init__.py
  forms-flow-api/src/formsflow_api/services/external/bpm.py
  forms-flow-api/src/formsflow_api/services/external/formio.py
  forms-flow-api/src/formsflow_api/utils/__init__.py
  forms-flow-api/src/formsflow_api/utils/caching.py
Labels: python

#532 Feat: Updating inference API response with prediction confidence score
  forms-flow-data-analysis-api/requirements/prod.txt
  forms-flow-data-analysis-api/src/api/config.py
  forms-flow-data-analysis-api/src/api/resources/sentiment_analysis.py
  forms-flow-data-analysis-api/src/api/services/transformers.py
  forms-flow-data-analysis-api/src/api/utils/auth.py
  forms-flow-data-analysis-api/tests/unit/api/test_sentiment_analysis.py
  forms-flow-data-analysis-api/tests/utilities/base_test.py
Labels: enhancement, python

#541 Feat: sentiment jobs update for sentiment analysis v2
  jobs/sentiment-analysis/config.py
  jobs/sentiment-analysis/sentiment_analysis.py
Labels: python

#536 Testcase for formio form creation
  .github/workflows/forms-flow-api-ci.yml
  forms-flow-api/tests/conftest.py
  forms-flow-api/tests/docker/docker-compose.yml
  forms-flow-api/tests/docker/nginx.conf
  forms-flow-api/tests/unit/api/test_form_process_mapper.py
  forms-flow-api/tests/utilities/base_test.py
  forms-flow-forms/api-spec/forms-flow-forms-api-spec.yaml
Labels: python
