Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2025-05, with the labels that each got.

#2724 bugix/fwf:4414 & 4586 changes to dmn and bpmn editor
  forms-flow-web/src/_tests_/unit/ClientTable.test.js
  forms-flow-web/src/_tests_/unit/SubmitList.test.js
  forms-flow-web/src/_tests_/unit/UserForm.test.js
  forms-flow-web/src/components/Modeler/Editors/DmnEditor/DmnEditor.js
  forms-flow-web/src/components/Modeler/Editors/Editor.scss
  forms-flow-web/src/routes/Submit/Forms/SubmitList.js
Labels: Review effort 3/5

#2726 FWF-4521 [Modify] Clean up of readme files
  DEPENDENCIES.md
  USAGE.md
  deployment/README.md
  forms-flow-analytics/README.md
  forms-flow-api/README.md
  forms-flow-bpm/README.md
  forms-flow-data-analysis-api/README.md
  forms-flow-documents/README.md
  forms-flow-forms/README.md
  forms-flow-idm/README.md
  forms-flow-idm/keycloak/README.md
  forms-flow-redis/README.md
  forms-flow-web-root-config/README.md
  forms-flow-web/README.md
Labels: Review effort 2/5

#2729 confirm modal prop typo fix
  forms-flow-web/__mocks__/@formsflow/components.js
  forms-flow-web/src/_tests_/unit/submissionAndDraftTable.test.js
  forms-flow-web/src/components/CustomComponents/NavigateBlocker.jsx
  forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
  forms-flow-web/src/routes/Design/Forms/FlowEdit.js
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
  forms-flow-web/src/routes/Design/Process/ProcessCreateEdit.js
Labels: Review effort 2/5

#2731 Fixed [bugfix] resetting submission related data, and it's errors
  forms-flow-web/src/routes/Submit/Forms/SubmitIndex.js
Labels: Review effort 2/5

#2733 updated register ftl file
  forms-flow-idm/keycloak/themes/formsflow/login/register.ftl
Labels: Review effort 2/5

#2737 FWF-4631-4628 [bugfix] fixed content component and date time component rendering
  forms-flow-web-root-config/sample.env
  forms-flow-web-root-config/src/index.ejs
Labels: Review effort 2/5

#2730 webapi: Feature/fwf 4504 task outcome configuration
  CHANGELOG.md
  forms-flow-api/migrations/versions/5ecbbfc545ba_task_outcome_configuration_table.py
  forms-flow-api/requirements/dev.txt
  forms-flow-api/src/formsflow_api/constants/__init__.py
  forms-flow-api/src/formsflow_api/models/tasks.py
  forms-flow-api/src/formsflow_api/resources/__init__.py
  forms-flow-api/src/formsflow_api/resources/tasks.py
  forms-flow-api/src/formsflow_api/schemas/__init__.py
  forms-flow-api/src/formsflow_api/schemas/tasks.py
  forms-flow-api/src/formsflow_api/services/__init__.py
  forms-flow-api/src/formsflow_api/services/tasks.py
  forms-flow-api/tests/unit/api/test_task.py
  forms-flow-api/tests/utilities/base_test.py
Labels: Review effort 3/5

#2740 FWF-4376:- change in the documents api name
  deployment/Individual-deployment/README.md
Labels: Review effort 1/5

#2741 Added [feature] added checking dependency pr in ci
  .github/pull_request_template.md
  .github/workflows/check-dependecy-pr.yml
Labels: Review effort 2/5

#2744 FWF-4652 [bugfix] added jwt token expire for formio token
  CHANGELOG.md
  deployment/docker/docker-compose.yml
  deployment/docker/sample.env
  deployment/openshift/sample.env
  forms-flow-api/docker-compose.yml
  forms-flow-api/sample.env
  forms-flow-api/src/formsflow_api/config.py
  forms-flow-api/src/formsflow_api/models/filter_preferences.py
  forms-flow-api/src/formsflow_api/resources/formio.py
  forms-flow-api/tests/unit/api/test_formio.py
  forms-flow-forms/sample.env
Labels: Review effort 2/5

#2748 Automate ticket status moving when pr merge to develop
  .github/workflows/ticket-status-merge.yml
Labels: Review effort 1/5

#2747 FWF-4664: [Feature] Add formId & parentFormId to application list api response
  forms-flow-api/src/formsflow_api/resources/application.py
  forms-flow-api/src/formsflow_api/services/application.py
  forms-flow-api/tests/unit/api/test_application.py
Labels: Review effort 2/5

#2751 Update ticket-status-merge.yml changed pull request to pull_request_target:
  .github/workflows/ticket-status-merge.yml
Labels: Review effort 2/5

#2752 Test Update ticket-status-merge.yml
  .github/workflows/ticket-status-merge.yml
Labels: Review effort 1/5

#2738 Added [FWF-4598] added form_name in submission query result
  forms-flow-data-layer/src/graphql/schema/submission_schema.py
  forms-flow-data-layer/src/graphql/service/submission_service.py
  forms-flow-data-layer/src/models/webapi/application.py
  forms-flow-data-layer/tests/resolvers/test_submissions.py
Labels: Review effort 2/5

#2753 bugfix/FWF-4659 [bugfix] client journey submission date fix
  forms-flow-web/src/components/Form/constants/ClientTable.js
Labels: Review effort 1/5

#2757 bugfix/FWF-4171 [bugfix] wizard button fix
  forms-flow-web/package-lock.json
  forms-flow-web/package.json
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
  forms-flow-web/src/routes/Design/Forms/FormPreview.js
  forms-flow-web/src/routes/Submit/Forms/UserForm.js
  forms-flow-web/src/routes/Submit/Forms/View.js
  forms-flow-web/src/routes/Submit/Submission/Item/Edit.js
  forms-flow-web/src/routes/Submit/Submission/Item/View.js
Labels: Review effort 2/5

#2758 bugfix/FWF-4659 [bugfix] submission date fix
  forms-flow-web/src/apiManager/services/bpmServices.js
Labels: Review effort 1/5

#2746 bugfix/FWF-4648-client-jurney [bugfix] initial fix for client journey
  forms-flow-web/__mocks__/@formsflow/components.js
  forms-flow-web/src/_tests_/unit/UserForm.test.js
  forms-flow-web/src/_tests_/unit/draftAndSubmissions.test.js
  forms-flow-web/src/_tests_/unit/routes/Design/Forms/list.test.js
  forms-flow-web/src/apiManager/services/applicationServices.js
  forms-flow-web/src/apiManager/services/formatterService.js
  forms-flow-web/src/components/Form/constants/ClientTable.js
  forms-flow-web/src/customHooks/useSuccessCountdown.js
  forms-flow-web/src/modules/applicationsReducer.js
  forms-flow-web/src/routes/Design/Forms/List.js
  forms-flow-web/src/routes/Submit/Forms/DraftAndSubmissions.js
  forms-flow-web/src/routes/Submit/Forms/UserForm.js
  forms-flow-web/src/routes/Submit/Forms/index.js
Labels: Review effort 3/5

#2745 FWF-4304: [Bugfix] Fix dashboard issues
  forms-flow-api/src/formsflow_api/models/authorization.py
  forms-flow-api/src/formsflow_api/resources/dashboards.py
  forms-flow-api/src/formsflow_api/services/authorization.py
  forms-flow-api/tests/unit/api/test_authorization.py
  forms-flow-api/tests/unit/api/test_dashboards.py
Labels: Review effort 4/5

#2756 FWF-4597 [Bugfix] Submission unauthorized issue if form is loaded as initial screen fixed
  forms-flow-web/src/components/PrivateRoute.jsx
Labels: Review effort 2/5

#2759 modified/FWF-4454 [modified] updated date format
  forms-flow-web/src/_tests_/unit/UserForm.test.js
  forms-flow-web/src/_tests_/unit/submissionAndDraftTable.test.js
  forms-flow-web/src/components/Form/constants/ClientTable.js
  forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
  forms-flow-web/src/helper/dateTimeHelper.js
  forms-flow-web/src/routes/Submit/Forms/UserForm.js
Labels: Review effort 3/5

#2760 modified/FWF-4454 [modified] fixed sort and view redirect issue
  forms-flow-web/src/_tests_/unit/ClientTable.test.js
  forms-flow-web/src/components/Form/constants/ClientTable.js
  forms-flow-web/src/modules/bpmFormReducer.js
  forms-flow-web/src/routes/Submit/Forms/SubmitList.js
  forms-flow-web/src/routes/Submit/Submission/SubmissionView.js
Labels: Review effort 3/5
