Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2025-06, with the labels that each got.

#2764 Bugfix/FWF 3740 update data test
  forms-flow-web/__mocks__/@formsflow/components.js
  forms-flow-web/src/components/CustomComponents/NavigateBlocker.jsx
  forms-flow-web/src/components/CustomComponents/SortableHeader.js
  forms-flow-web/src/components/Form/components/FormSettings.js
  forms-flow-web/src/components/Modals/CreateFormModal.js
  forms-flow-web/src/components/Modals/ExportModal.js
  forms-flow-web/src/components/Modals/NewVersionModal.js
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
Labels: Review effort 3/5

#2761 FWF-4620: [Feature] Migration of task filters
  forms-flow-api/migrations/versions/c384c1ce7cd7_task_filter_migration.py
  forms-flow-api/src/formsflow_api/constants/__init__.py
  forms-flow-api/src/formsflow_api/models/filter.py
  forms-flow-api/src/formsflow_api/resources/filter.py
  forms-flow-api/src/formsflow_api/schemas/filter.py
  forms-flow-api/src/formsflow_api/services/filter.py
  forms-flow-api/tests/unit/api/test_filter.py
  forms-flow-api/tests/utilities/base_test.py
Labels: Review effort 4/5

#2772 feat: add GitHub Actions workflow to send Google Chat alert on new issue
  .github/workflows/google-chat-issue-alert.yml
Labels: Review effort 2/5

#2777 [BugFix]: null check added for taskVisibileAttributes in task page,listener hyperlink updated in changelog
  CHANGELOG.md
  forms-flow-web/src/components/ServiceFlow/list/TaskVariable.js
Labels: Review effort 2/5

#2785 Feature: API authorization based on new permissions
  CHANGELOG.md
  forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
  forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
  forms-flow-api/requirements.txt
  forms-flow-api/requirements/prod.txt
  forms-flow-api/src/formsflow_api/resources/application_history.py
  forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
  forms-flow-api/src/formsflow_api/resources/metrics.py
  forms-flow-api/src/formsflow_api/resources/process.py
  forms-flow-api/src/formsflow_api/resources/roles.py
  forms-flow-api/src/formsflow_api/resources/theme.py
  forms-flow-api/src/formsflow_api/resources/user.py
  forms-flow-api/src/formsflow_api/services/process.py
  forms-flow-api/tests/docker/realms/forms-flow-ai-realm.json
  forms-flow-api/tests/unit/api/test_application_history.py
  forms-flow-api/tests/unit/api/test_metrics.py
  forms-flow-api/tests/unit/api/test_process.py
  forms-flow-api/tests/unit/api/test_roles.py
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml
Labels: Review effort 4/5

#2784 modified/FWF-4785-permission [modified] updated permission in opensource
  forms-flow-web/src/_tests_/unit/draftAndSubmissions.test.js
  forms-flow-web/src/_tests_/unit/mockState.js
  forms-flow-web/src/components/Form/constants/FormTable.js
  forms-flow-web/src/components/Modals/ActionModal.js
  forms-flow-web/src/components/Modals/SettingsModal.js
  forms-flow-web/src/components/Modals/TaskVariableModal.js
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/constants/constants.js
  forms-flow-web/src/constants/permissions.js
  forms-flow-web/src/routes/Design/Forms/FlowEdit.js
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
  forms-flow-web/src/routes/Design/Forms/List.js
  forms-flow-web/src/routes/Submit/Forms/DraftAndSubmissions.js
  forms-flow-web/src/routes/Submit/Forms/SubmitList.js
  forms-flow-web/src/routes/Submit/Submission/SubmissionView.js
Labels: Review effort 4/5

#2787 Update check-dependecy-pr.yml
  .github/workflows/check-dependecy-pr.yml
Labels: Review effort 1/5

#2795 updated permission
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/constants/permissions.js
  forms-flow-web/src/routes/Submit/Forms/SubmitIndex.js
  forms-flow-web/src/routes/Submit/Submission/index.js
Labels: Review effort 2/5

#2797 API: [Feature] Add filter preference to attribute/field filter
  forms-flow-api/src/formsflow_api/models/filter.py
  forms-flow-api/src/formsflow_api/models/filter_preferences.py
  forms-flow-api/src/formsflow_api/resources/filter.py
  forms-flow-api/src/formsflow_api/services/filter.py
  forms-flow-api/src/formsflow_api/services/filter_preference.py
Labels: Review effort 4/5

#2799 Fwf 4851
  forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
  forms-flow-api/requirements.txt
  forms-flow-api/requirements/prod.txt
  forms-flow-api/src/formsflow_api/resources/application.py
  forms-flow-api/src/formsflow_api/resources/formio.py
Labels: Review effort 2/5

#2803 FWF-4863 [modified] prevent api call based on permission
  forms-flow-web/src/routes/Submit/Submission/SubmissionView.js
Labels: Review effort 2/5

#2804 [update] Change formsflow_api_utils repository reference to aot-techologies on develop branch
  forms-flow-api/requirements.txt
  forms-flow-api/requirements/prod.txt
  forms-flow-documents/requirements.txt
  forms-flow-documents/requirements/prod.txt
Labels: Review effort 1/5

#2805 [Bugfix] Removed ; from graphql env
  deployment/docker/sample.env
Labels: Review effort 1/5

#2806 updated permssion
  forms-flow-api-utils/src/formsflow_api_utils/utils/util.py
Labels: Review effort 2/5

#2808 route fix for analyse submision and documents permission update
  forms-flow-documents/src/formsflow_documents/resources/pdf.py
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/routes/Submit/Submission/SubmissionView.js
Labels: Review effort 2/5

#2809 Master 7.0.1 to develop
  CHANGELOG.md
  README.md
  forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py
  forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
  forms-flow-api/src/formsflow_api/services/form_process_mapper.py
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/commons/connector/HTTPServiceInvoker.java
  forms-flow-web-root-config/src/formsflow-root-config.js
  forms-flow-web/scripts/package-lock.json
  forms-flow-web/scripts/package.json
  forms-flow-web/src/components/BaseRouting.jsx
  forms-flow-web/src/components/ServiceFlow/ServiceFlow.scss
  forms-flow-web/src/containers/TaskHead.js
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
Labels: Review effort 4/5

#2811 Updated docker-compose with data-layer and sample.env as well
  deployment/docker/docker-compose.yml
  deployment/docker/sample.env
Labels: Review effort 2/5

#2810 updated permission
  forms-flow-api/src/formsflow_api/resources/application.py
  forms-flow-api/tests/unit/api/test_draft.py
Labels: Review effort 2/5

#2813 Fixed diagram container height
  forms-flow-web/src/components/BPMN/BpmnViewer.js
  forms-flow-web/src/components/Modeler/Editors/BpmnEditor/BpmEditor.js
  forms-flow-web/src/components/Modeler/Editors/DmnEditor/DmnEditor.js
  forms-flow-web/src/components/Modeler/Editors/Editor.scss
Labels: Review effort 2/5

#2828 FWF-4884: Documents API fixes
  forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py
  forms-flow-documents/src/formsflow_documents/app.py
  forms-flow-documents/src/formsflow_documents/resources/pdf.py
  forms-flow-documents/src/formsflow_documents/templates/index.html
Labels: Review effort 2/5

#2830 Latest develop to 7.1.0
  .images/image_data_layer.png
  deployment/Individual-deployment/README.md
  forms-flow-api-utils/src/formsflow_api_utils/utils/pdf.py
  forms-flow-api/requirements.txt
  forms-flow-api/requirements/prod.txt
  forms-flow-documents/src/formsflow_documents/app.py
  forms-flow-documents/src/formsflow_documents/resources/pdf.py
  forms-flow-documents/src/formsflow_documents/static/css/bootstrap.min.css
  forms-flow-documents/src/formsflow_documents/static/css/font-awesome.min.css
  forms-flow-documents/src/formsflow_documents/static/css/formio.full.min.css
  forms-flow-documents/src/formsflow_documents/static/js/customformio.js
  forms-flow-documents/src/formsflow_documents/static/js/formio.full.min.js
  forms-flow-documents/src/formsflow_documents/templates/index.html
  forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
  forms-flow-web/src/helper/routerHelper.js
  forms-flow-web/src/routes/Submit/Forms/index.js
  forms-flow-web/src/routes/Submit/Submission/Item/ResubmitForm.js
  forms-flow-web/src/routes/Submit/Submission/SubmissionView.js
Labels: Review effort 4/5

#2836 🚀 Develop to Release 7.1.0
  forms-flow-web-root-config/src/index.ejs
  forms-flow-web-root-config/src/microfrontend-layout.html
  forms-flow-web-root-config/src/microfrontend-multitenant-layout.html
  forms-flow-web/src/components/PrivateRoute.jsx
  forms-flow-web/src/components/ServiceFlow/details/ServiceTaskDetails.js
  forms-flow-web/src/components/ServiceFlow/index.js
  forms-flow-web/src/components/ServiceFlow/list/ServiceTaskList.js
  forms-flow-web/src/constants/constants.js
Labels: Review effort 3/5

#2838 updated structure
  forms-flow-documents/sample.env
  forms-flow-documents/src/formsflow_documents/templates/index.html
Labels: Review effort 2/5

#2834 📜 v7.1.0 Changelog updates
  .images/add-permissions.png
  CHANGELOG.md
  DEPENDENCIES.md
  deployment/docker/README.md
  deployment/docker/sample.env
  forms-flow-analytics/README.md
  forms-flow-api-utils/README.md
  forms-flow-api/README.md
  forms-flow-data-analysis-api/README.md
  forms-flow-documents/README.md
  forms-flow-documents/sample.env
  forms-flow-idm/README.md
  forms-flow-idm/migration/README.md
  forms-flow-web-root-config/sample.env
  forms-flow-web/sample.env
Labels: Review effort 2/5

#2842 🚀 Develop to Release 7.1.0
  .images/add-permissions.png
  CHANGELOG.md
  DEPENDENCIES.md
  deployment/docker/README.md
  deployment/docker/sample.env
  forms-flow-analytics/README.md
  forms-flow-api-utils/README.md
  forms-flow-api/README.md
  forms-flow-bpm/Dockerfile
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/resources/application.yaml
  forms-flow-bpm/sslcom.cer
  forms-flow-data-analysis-api/README.md
  forms-flow-documents/README.md
  forms-flow-documents/sample.env
  forms-flow-documents/src/formsflow_documents/templates/index.html
  forms-flow-idm/README.md
  forms-flow-idm/migration/README.md
  forms-flow-web-root-config/sample.env
  forms-flow-web/sample.env
  forms-flow-web/src/components/Dashboard/Dashboard.js
  forms-flow-web/src/components/Dashboard/dashboard.scss
  forms-flow-web/src/components/Modeler/Editors/Editor.scss
Labels: Review effort 3/5
