Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2025-08, with the labels that each got.

#2895 🐛 FWF-4940: [Bugfix] Datalayer: Fix Transaction not restarting when there's error in webapi query
  forms-flow-data-layer/src/db/sql_base.py
  forms-flow-data-layer/src/models/webapi/base.py
Labels: Review effort 2/5

#2884 FWF-4482 [vulnerability fix] vulnerability fix
  forms-flow-web-root-config/package-lock.json
  forms-flow-web-root-config/package.json
  forms-flow-web/package-lock.json
  forms-flow-web/package.json
Labels: Review effort 2/5

#2885 bugfix/FWF-5042 [bugfix] updated permission on workflow
  forms-flow-web/src/routes/Design/Process/ProcessTable.js
  forms-flow-web/src/routes/Design/Process/index.js
Labels: Review effort 2/5

#2896 FWF-4956:[Bugfix] - WEB bugfixes
  forms-flow-web/src/_tests_/unit/mockState.js
  forms-flow-web/src/_tests_/unit/rootReducer.js
  forms-flow-web/src/components/Application/ApplicationTable.js
  forms-flow-web/src/components/Draft/DraftTable.js
  forms-flow-web/src/components/Form/constants/ClientTable.js
  forms-flow-web/src/components/Form/constants/FormTable.js
  forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
  forms-flow-web/src/components/Form/constants/table.js
  forms-flow-web/src/modules/bpmFormReducer.js
  forms-flow-web/src/modules/index.js
  forms-flow-web/src/routes/Design/Process/ProcessTable.js
  forms-flow-web/src/routes/Submit/Forms/SubmitList.js
Labels: Review effort 3/5

#2899 [Testing] Enable debug mode in web to test application in debug mode
  forms-flow-web/craco.config.js
  forms-flow-web/package.json
Labels: Review effort 2/5

#2900 Include type to analyze submission filter variables
  forms-flow-api/src/formsflow_api/resources/submissions_filter.py
  forms-flow-api/src/formsflow_api/schemas/submissions_filter.py
  forms-flow-api/tests/unit/api/test_submissions_filter.py
Labels: Review effort 2/5

#2883 IDM: Feature/fwf 4669 Add migrate permissions to the existing groups 7 to 7.1
  CHANGELOG.md
  forms-flow-idm/README.md
  forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
  forms-flow-idm/migration/README.md
  forms-flow-idm/migration/migrate-7.2.0.py
  forms-flow-idm/migration/utils.py
  forms-flow-idm/realm-exports/Group based auth.json
Labels: Review effort 3/5

#2901 Bugfix: Refactor error handling for role creation to use more descriptive error message
  forms-flow-api/src/formsflow_api/constants/__init__.py
  forms-flow-api/src/formsflow_api/services/factory/keycloak_group_service.py
Labels: Review effort 2/5

#2907 [Bugfix] Datalayer: Add date filtering in form fields
  forms-flow-data-layer/src/models/formio/submission.py
Labels: Review effort 2/5

#2910 [Feature] Webapi: Add new param in formlist API to list all forms(active&inactive)
  CHANGELOG.md
  forms-flow-api/src/formsflow_api/models/form_process_mapper.py
  forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
  forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
  forms-flow-api/src/formsflow_api/services/form_process_mapper.py
Labels: Review effort 2/5

#2913 [SYNC] Develop to 7.2.0-rc updated
  .github/workflows/forms-flow-api-cd.yml
  .github/workflows/qa-deployment.yml
  CHANGELOG.md
  forms-flow-api/src/formsflow_api/models/form_process_mapper.py
  forms-flow-api/src/formsflow_api/resources/form_process_mapper.py
  forms-flow-api/src/formsflow_api/schemas/form_process_mapper.py
  forms-flow-api/src/formsflow_api/services/form_process_mapper.py
  forms-flow-data-layer/src/graphql/service/submission_service.py
  forms-flow-data-layer/src/models/formio/submission.py
  forms-flow-data-layer/src/utils/__init__.py
  forms-flow-data-layer/src/utils/datetime_utils.py
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
  forms-flow-web/src/routes/Submit/Forms/UserForm.js
  forms-flow-web/src/routes/Submit/Submission/Item/ResubmitForm.js
Labels: Review effort 3/5

#2914 [Bugfix] Datalayer: Fix sort on form fields working for individual pages & Enhance list of string responses
  forms-flow-data-layer/src/graphql/service/submission_service.py
  forms-flow-data-layer/src/utils/datetime_utils.py
Labels: Review effort 2/5

#2919 FWF-5202 : [HotFix] Fixed language error in history --> view submission page
  forms-flow-web/src/components/PrivateRoute.jsx
Labels: Review effort 2/5

#2876 bugfix/multi-tenancy updated fix for multi tenancy
  forms-flow-web/src/apiManager/services/formFormatterService.js
  forms-flow-web/src/components/Form/components/FormSettings.js
  forms-flow-web/src/helper/helper.js
  forms-flow-web/src/routes/Design/Forms/FormEdit.js
Labels: Review effort 2/5

#2921 FWF-5221:[Feature] - Updated Class in Resubmit Page
  forms-flow-web/src/routes/Submit/Submission/Item/ResubmitForm.js
Labels: Review effort 1/5

#2916 FWF-5146: Refactor datetime conversion to return ISO string format with milliseconds and 'Z'
  forms-flow-data-layer/src/utils/datetime_utils.py
Labels: Review effort 2/5

#2920 [🐛Bugfix] Documents-API: Fix custom pdf download extending template.html is failing
  forms-flow-documents/src/formsflow_documents/services/pdf.py
Labels: Review effort 2/5
