Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2025-04, with the labels that each got.

#2722 Update pr_review_agent.yml
  .github/workflows/pr_review_agent.yml
Labels: Review effort 1/5

#2720 FWF-4516: [Feature] Added submissions micro front end module
  .github/workflows/forms-flow-root-config-cd.yml
  deployment/docker/docker-compose.yml
  deployment/docker/sample.env
  forms-flow-web-root-config/Dockerfile
  forms-flow-web-root-config/docker-compose.yml
  forms-flow-web-root-config/public/config/config.template.js
  forms-flow-web-root-config/sample.env
  forms-flow-web-root-config/src/index.ejs
  forms-flow-web-root-config/src/microfrontend-layout.html
  forms-flow-web-root-config/src/microfrontend-multitenant-layout.html
Labels: Review effort 2/5

#2725 FWF-4497: [Feature] Add view_process_diagram depends on view_history_permission
  forms-flow-api-utils/src/formsflow_api_utils/utils/permisions.py
Labels: Review effort 1/5

#2711 FWF-4488: [Bugfix] Return latest submission in client form list
  forms-flow-api/src/formsflow_api/models/application.py
  forms-flow-api/src/formsflow_api/schemas/base_schema.py
Labels: Review effort 3/5

#2714 FWF-4541 [feature] restructured data layer code and removed sample codes
  .github/workflows/forms-flow-data-layer-ci.yml
  .github/workflows/forms-flow-web-ci.yml
  forms-flow-data-layer/sample.env
  forms-flow-data-layer/src/graphql/resolvers/__init__.py
  forms-flow-data-layer/src/graphql/resolvers/formio_form_resolvers.py
  forms-flow-data-layer/src/graphql/resolvers/submission_resolvers.py
  forms-flow-data-layer/src/graphql/schema/__init__.py
  forms-flow-data-layer/src/graphql/schema/form_schema.py
  forms-flow-data-layer/src/graphql/schema/submission_schema.py
  forms-flow-data-layer/src/graphql/service/__init__.py
  forms-flow-data-layer/src/graphql/service/form_service.py
  forms-flow-data-layer/src/graphql/service/formio_form_service.py
  forms-flow-data-layer/src/graphql/service/submission_service.py
  forms-flow-data-layer/src/models/formio/__init__.py
  forms-flow-data-layer/src/models/formio/constants.py
  forms-flow-data-layer/src/models/formio/form.py
  forms-flow-data-layer/src/models/formio/submission.py
  forms-flow-data-layer/src/models/webapi/__init__.py
  forms-flow-data-layer/src/models/webapi/application.py
  forms-flow-data-layer/src/models/webapi/authorization.py
  forms-flow-data-layer/src/models/webapi/base.py
  forms-flow-data-layer/src/models/webapi/constants.py
  forms-flow-data-layer/src/models/webapi/formprocess_mapper.py
  forms-flow-data-layer/tests/conftest.py
  forms-flow-data-layer/tests/resolvers/test_formio_form.py
  forms-flow-data-layer/tests/resolvers/test_submissions.py
  forms-flow-data-layer/tests/utils.py
Labels: Review effort 4/5
