Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2025-03, with the labels that each got.

#2614 ❇️ FWF-4372 [feature] Added new service forms-flow-data-layer
  .github/workflows/forms-flow-data-layer-ci.yml
  forms-flow-data-layer/.gitignore
  forms-flow-data-layer/Dockerfile
  forms-flow-data-layer/README.md
  forms-flow-data-layer/docker-compose.yml
  forms-flow-data-layer/main.py
  forms-flow-data-layer/requirements.txt
  forms-flow-data-layer/requirements/base.txt
  forms-flow-data-layer/requirements/dev.txt
  forms-flow-data-layer/sample.env
  forms-flow-data-layer/setup.cfg
  forms-flow-data-layer/src/__init__.py
  forms-flow-data-layer/src/config/envs.py
  forms-flow-data-layer/src/db/__init__.py
  forms-flow-data-layer/src/db/formio_db.py
  forms-flow-data-layer/src/db/redis_client.py
  forms-flow-data-layer/src/graphql/resolvers/__init__.py
  forms-flow-data-layer/src/graphql/resolvers/formio_form_resolvers.py
  forms-flow-data-layer/src/graphql/schema/__init__.py
  forms-flow-data-layer/src/graphql/schema/formio_form_schema.py
  forms-flow-data-layer/src/graphql/service/__init__.py
  forms-flow-data-layer/src/graphql/service/formio_form_service.py
  forms-flow-data-layer/src/graphql/setup.py
  forms-flow-data-layer/src/models/formio/__init__.py
  forms-flow-data-layer/src/models/formio/form.py
  forms-flow-data-layer/src/utils/__init__.py
  forms-flow-data-layer/src/utils/cache_helper.py
  forms-flow-data-layer/tests/__init__.py
  forms-flow-data-layer/tests/conftest.py
  forms-flow-data-layer/tests/resolvers/test_formio_form.py
Labels: Feature

#2596 Feature/fwf 4371 Backend support different filter types
  CHANGELOG.md
  forms-flow-api/migrations/versions/92bf83135905_add_filter_type_parent_filterid_filter_table.py
  forms-flow-api/src/formsflow_api/models/__init__.py
  forms-flow-api/src/formsflow_api/models/filter.py
  forms-flow-api/src/formsflow_api/resources/filter.py
  forms-flow-api/src/formsflow_api/schemas/filter.py
  forms-flow-api/src/formsflow_api/services/filter.py
  forms-flow-api/tests/unit/api/test_filter.py
  forms-flow-api/tests/utilities/base_test.py
Labels: enhancement

#2658 ❇️ Feature/fwf 4405 authentication for data layer
  .github/workflows/forms-flow-data-layer-cd.yml
  forms-flow-data-layer/.dockerignore
  forms-flow-data-layer/.gitignore
  forms-flow-data-layer/Dockerfile
  forms-flow-data-layer/docker-compose.yml
  forms-flow-data-layer/main.py
  forms-flow-data-layer/requirements.txt
  forms-flow-data-layer/requirements/base.txt
  forms-flow-data-layer/sample.env
  forms-flow-data-layer/setup.cfg
  forms-flow-data-layer/src/__init__.py
  forms-flow-data-layer/src/config/envs.py
  forms-flow-data-layer/src/db/__init__.py
  forms-flow-data-layer/src/db/bpmn_db.py
  forms-flow-data-layer/src/db/formio_db.py
  forms-flow-data-layer/src/db/redis_client.py
  forms-flow-data-layer/src/db/sql_base.py
  forms-flow-data-layer/src/db/webapi_db.py
  forms-flow-data-layer/src/graphql/resolvers/formio_form_resolvers.py
  forms-flow-data-layer/src/graphql/resolvers/submission_resolvers.py
  forms-flow-data-layer/src/graphql/schema/formio_form_schema.py
  forms-flow-data-layer/src/graphql/schema/submission_schema.py
  forms-flow-data-layer/src/graphql/service/formio_form_service.py
  forms-flow-data-layer/src/graphql/service/submission_service.py
  forms-flow-data-layer/src/graphql/setup.py
  forms-flow-data-layer/src/middlewares/auth.py
  forms-flow-data-layer/src/middlewares/role_check.py
  forms-flow-data-layer/src/routes/__init__.py
  forms-flow-data-layer/src/routes/health.py
  forms-flow-data-layer/src/utils/__init__.py
  forms-flow-data-layer/src/utils/cache_helper.py
  forms-flow-data-layer/src/utils/keycloak_oidc.py
  forms-flow-data-layer/src/utils/logger.py
  forms-flow-data-layer/src/utils/user_context.py
  forms-flow-data-layer/tests/conftest.py
  forms-flow-data-layer/tests/resolvers/test_submissions.py
Labels: Feature

#2672 FWF-4396 [feature] filter preference table created for saving user's filter preferences
  CHANGELOG.md
  forms-flow-api/migrations/versions/a5d9bbf7b5ac_filter_preference_table_created.py
  forms-flow-api/src/formsflow_api/constants/__init__.py
  forms-flow-api/src/formsflow_api/models/__init__.py
  forms-flow-api/src/formsflow_api/models/filter.py
  forms-flow-api/src/formsflow_api/models/filter_preferences.py
  forms-flow-api/src/formsflow_api/resources/filter.py
  forms-flow-api/src/formsflow_api/schemas/__init__.py
  forms-flow-api/src/formsflow_api/schemas/filter.py
  forms-flow-api/src/formsflow_api/schemas/filter_preference.py
  forms-flow-api/src/formsflow_api/services/__init__.py
  forms-flow-api/src/formsflow_api/services/filter.py
  forms-flow-api/src/formsflow_api/services/filter_preference.py
  forms-flow-api/tests/unit/api/test_filter.py
Labels: enhancement, python, Feature
