Repository AOT-Technologies/forms-flow-ai, pull requests merged in 2025-07, with the labels that each got.

#2845 Update CHANGELOG.md to add known issue & Graphql url uncommented in rootconfig
  CHANGELOG.md
  forms-flow-web-root-config/sample.env
Labels: Review effort 1/5

#2833 Expose Camunda API: delete APIs added to the gateway
  CHANGELOG.md
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/DeploymentRestResource.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessDefinitionRestResource.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/ProcessInstanceRestResource.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/TaskRestResource.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/DeploymentRestResourceImpl.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessDefinitionRestResourceImpl.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/ProcessInstanceRestResourceImpl.java
  forms-flow-bpm/forms-flow-bpm-camunda/src/main/java/org/camunda/bpm/extension/hooks/rest/impl/TaskRestResourceImpl.java
Labels: Review effort 3/5

#2849 Update README.md updated version in readme file and removed ci tags from there
  README.md
Labels: Review effort 1/5

#2854 FWF-4923: [Feature] Added parentFormId to` /form?activeForms=true` response
  .github/workflows/forms-flow-data-layer-ci.yml
  forms-flow-api/src/formsflow_api/models/form_process_mapper.py
  forms-flow-data-layer/src/models/formio/submission.py
Labels: Review effort 2/5

#2855 FWF-4917: [Feature] Add date filters to submission queries in GraphQL resolvers and services
  forms-flow-data-layer/src/graphql/resolvers/submission_resolvers.py
  forms-flow-data-layer/src/graphql/service/submission_service.py
  forms-flow-data-layer/src/models/webapi/application.py
Labels: Review effort 2/5

#2858 Bugfix/fwf 4804 fixed flow import
  forms-flow-api/src/formsflow_api/services/import_support.py
  forms-flow-api/src/formsflow_api/services/process.py
Labels: Review effort 2/5

#2870 FWF-4958:[Bugfix] - Added classes to handle custom header and wizard …
  forms-flow-web/src/routes/Submit/Submission/Item/View.js
Labels: Review effort 2/5

#2868 FWF-4505 [Feature] form component UI updates
  forms-flow-web/__mocks__/@formsflow/components.js
  forms-flow-web/src/components/Application/ApplicationTable.js
  forms-flow-web/src/components/CustomComponents/SortableHeader.js
  forms-flow-web/src/components/Draft/DraftTable.js
  forms-flow-web/src/components/Form/constants/ClientTable.js
  forms-flow-web/src/components/Form/constants/FormTable.js
  forms-flow-web/src/components/Form/constants/SubmissionsAndDraftTable.js
  forms-flow-web/src/routes/Design/Process/ProcessTable.js
Labels: Review effort 4/5

#2873 feature/fwf-4654: Added new variable selection modal
  forms-flow-web/src/routes/Design/Forms/FlowEdit.js
Labels: Review effort 3/5

#2743 FWF - 4564 [Feature] implement a git commit msg hook to show a warning to user when a commit is done
  CHANGELOG.md
  forms-flow-tools/README.md
  forms-flow-tools/custom-hooks/pre-push
  forms-flow-tools/install-hooks.sh
  git-hooks/install-pre-push.sh
  git-hooks/pre-push
  package-lock.json
Labels: Review effort 3/5

#2866 FWF-4918: Keycloak migration of new roles in multitenant setup
  CHANGELOG.md
  forms-flow-idm/README.md
  forms-flow-idm/migration/README.md
  forms-flow-idm/migration/migrate-7.1.0.py
  forms-flow-idm/migration/migrate-7.2.0.py
  forms-flow-idm/migration/utils.py
Labels: Review effort 2/5

#2872 FWF-4975: [Modified] Updated create_filters description
  CHANGELOG.md
  forms-flow-api-utils/src/formsflow_api_utils/utils/__init__.py
  forms-flow-api-utils/src/formsflow_api_utils/utils/permissions.py
  forms-flow-api-utils/src/formsflow_api_utils/utils/test_utils.py
  forms-flow-api-utils/src/formsflow_api_utils/utils/util.py
  forms-flow-api/tests/docker/realms/forms-flow-ai-realm.json
  forms-flow-idm/keycloak/imports/formsflow-ai-realm.json
  forms-flow-idm/realm-exports/Group based auth.json
Labels: Review effort 2/5

#2882 FWF-5114: Add default submissions filter to analyze submission filter list API response
  forms-flow-api/src/formsflow_api/resources/submissions_filter.py
  forms-flow-api/src/formsflow_api/services/submissions_filter.py
  forms-flow-api/tests/unit/api/test_submissions_filter.py
Labels: Review effort 2/5

#2887 FWF-5106: Update dependencies in requirements files to latest versions
  CHANGELOG.md
  DEPENDENCIES.md
  forms-flow-api/README.md
  forms-flow-api/requirements.txt
  forms-flow-data-analysis-api/README.md
  forms-flow-data-analysis-api/model_training/requirements.txt
  forms-flow-data-analysis-api/requirements.txt
  forms-flow-data-layer/requirements.txt
  forms-flow-documents/requirements.txt
  jobs/sentiment-analysis/requirements.txt
Labels: Review effort 3/5
